theme: minima
title: Ordering Simulator 2023 | Devlog
author: David Cao, Thomas Wang, Jeremy Lei
description: Blog for David Cao, Thomas Wang, and Jeremy Lei's CSE 165 final project: Ordering Simulator 2023.
